name: Bug Report
description: File a bug report.
title: "[BUG] "
labels:
  - bug
assignees:
  - glektarssza
body:
  - type: textarea
    id: short-description
    attributes:
      label: Description
      description: A short, concise description of what went wrong.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: The steps you followed to cause the issue.
    validations:
      required: true
  - type: textarea
    id: expected-results
    attributes:
      label: Expected Results
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual-results
    attributes:
      label: Actual Results
      description: What actually happened.
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: The operating system you are using.
    validations:
      required: true
  - type: input
    id: launcher
    attributes:
      label: Launcher
      description: The launcher you are using, if applicable.
    validations:
      required: false
  - type: input
    id: java-version
    attributes:
      label: Java Version
      description: The version of Java you are using.
    validations:
      required: true
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: The version of Java you are using.
    validations:
      required: true
  - type: input
    id: forge-version
    attributes:
      label: Forge Version
      description: The version of the Forge Mod Loader you are using.
    validations:
      required: true
  - type: dropdown
    id: using-optifine
    attributes:
      label: Optifine
      description: Are you using Optifine?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information you think would be relevant/helpful.
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Confirmations
      description: "I confirm that the following is true:"
      options:
        - label: I searched for other issues similar to mine and found none.
          required: true
        - label: "I am using this specific fork of the Create: Above and Beyond modpack and not the CurseForge version."
          required: true
        - label: "I am not encountering this issue with the CurseForge version of the Create: Above and Beyond modpack."
          required: true
